trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_TAG: 'latest'  # <-- Replace with actual tag if needed
  DOCKER_IMAGE: 'uipathprod.azurecr.io/robot/uiautomation-runtime:latest24.10'
  LICENSE_AGREEMENT: 'accept'
  ORCHESTRATOR_URL: 'https://cloud.uipath.com/walmazwnmqbk/DefaultTenant/orchestrator_'
  MACHINE_KEY: '2f331945-11ab-4c20-8d73-cf366516f9d4'

stages:
  - stage: Run_UiPath_Robot
    jobs:
      - job: RunOnLinux
        steps:
          - script: |
              echo "Pulling Docker image: $(DOCKER_IMAGE)"
              docker pull $(DOCKER_IMAGE)
            displayName: 'Docker Pull'

          - script: |
              echo "Running UiPath robot container"
              docker run -e LICENSE_AGREEMENT=$(LICENSE_AGREEMENT) \
                         -e ORCHESTRATOR_URL=$(ORCHESTRATOR_URL) \
                         -e MACHINE_KEY=$(MACHINE_KEY) \
                         -tid $(DOCKER_IMAGE)
            displayName: 'Docker Run UiPath Robot'
          - task: UiPathTest@5
            inputs:
              testTarget: 'TestSet'
              orchestratorConnection: 'UiPath_Testing'
              testSet: 'LinuxTestset'
              folderName: 'Test'