trigger:
  - master
variables:
  - group: DEV

stages:
  - stage: Build
    displayName: Build Package
    jobs: 
    - job: BuildPackage
      pool: Default
      steps:    
      - task: UiPathPack@2
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Process'
          orchestratorConnection: 'UiPath_Testing'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop

  - stage: Assest
    displayName: Create Assests
    jobs:
      - job: CreateAssests
        pool: Default
        steps:
        - task: UiPathAssets@2
          inputs:
            orchestratorConnection: 'UiPath_Testing'
            folderName: 'Modern Example'
            assetActionType: 'Deploy'
            csvFile: '$(Build.SourcesDirectory)\Data\Assests.csv'

  
  